# Generated by Django 6.1.1 on 2026-09-06 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_auditlog_case_caseaction_event_case_primary_event_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightStatusRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_number", models.CharField(max_length=50)),
                ("date", models.CharField(max_length=20)),
                ("origin_airport", models.CharField(blank=True, max_length=50)),
                ("destination_airport", models.CharField(blank=True, max_length=50)),
                ("scheduled_departure", models.DateTimeField(blank=True, null=True)),
                ("estimated_departure", models.DateTimeField(blank=True, null=True)),
                ("scheduled_arrival", models.DateTimeField(blank=True, null=True)),
                ("estimated_arrival", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(max_length=50)),
                ("gate", models.CharField(blank=True, max_length=20)),
                ("terminal", models.CharField(blank=True, max_length=20)),
                ("delay_minutes", models.IntegerField(default=0)),
                ("delay_reason", models.TextField(blank=True)),
                ("reported_at", models.DateTimeField()),
                (
                    "itinerary_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flight_status_records",
                        to="app.itineraryelement",
                    ),
                ),
            ],
            options={
                "ordering": ["-reported_at"],
            },
        ),
        migrations.CreateModel(
            name="GuidePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("speed_kmh", models.FloatField(default=0.0)),
                ("heading_deg", models.FloatField(default=0.0)),
                ("altitude_m", models.FloatField(default=0.0)),
                ("captured_at", models.DateTimeField()),
                ("received_at", models.DateTimeField()),
                (
                    "itinerary_element",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guide_positions",
                        to="app.itineraryelement",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guide_positions",
                        to="app.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="TrafficRouteRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(blank=True, max_length=255)),
                ("destination", models.CharField(blank=True, max_length=255)),
                ("departure_time", models.DateTimeField(blank=True, null=True)),
                ("distance_km", models.FloatField(default=0.0)),
                ("duration_minutes", models.FloatField(default=0.0)),
                ("traffic_delay_minutes", models.FloatField(default=0.0)),
                ("congestion_level", models.CharField(max_length=20)),
                ("recommended_route", models.CharField(blank=True, max_length=255)),
                ("incidents", models.JSONField(blank=True, default=list)),
                ("checked_at", models.DateTimeField()),
                (
                    "itinerary_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traffic_route_records",
                        to="app.itineraryelement",
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainStatusRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("train_number", models.CharField(max_length=50)),
                ("date", models.CharField(max_length=20)),
                ("origin_station", models.CharField(blank=True, max_length=255)),
                ("destination_station", models.CharField(blank=True, max_length=255)),
                ("current_station", models.CharField(blank=True, max_length=255)),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                ("estimated_time", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(max_length=50)),
                ("platform", models.CharField(blank=True, max_length=20)),
                ("delay_minutes", models.IntegerField(default=0)),
                ("speed_kmh", models.FloatField(default=0.0)),
                ("reported_at", models.DateTimeField()),
                (
                    "itinerary_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="train_status_records",
                        to="app.itineraryelement",
                    ),
                ),
            ],
            options={
                "ordering": ["-reported_at"],
            },
        ),
        migrations.CreateModel(
            name="WeatherRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                ("condition", models.CharField(blank=True, max_length=100)),
                ("temperature_c", models.FloatField(blank=True, null=True)),
                ("temperature_f", models.FloatField(blank=True, null=True)),
                ("humidity_percent", models.FloatField(default=0.0)),
                ("wind_speed_kmh", models.FloatField(default=0.0)),
                ("precipitation_mm", models.FloatField(default=0.0)),
                ("visibility_km", models.FloatField(default=0.0)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("checked_at", models.DateTimeField()),
                (
                    "itinerary_element",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_records",
                        to="app.itineraryelement",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weather_records",
                        to="app.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_at"],
            },
        ),
        migrations.CreateModel(
            name="NodeStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("classification", models.CharField(max_length=50)),
                ("severity", models.CharField(max_length=50)),
                ("reason", models.TextField(blank=True)),
                ("calculated_at", models.DateTimeField()),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="node_statuses",
                        to="app.case",
                    ),
                ),
                (
                    "itinerary_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_statuses",
                        to="app.itineraryelement",
                    ),
                ),
                (
                    "source_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="node_statuses",
                        to="app.event",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_statuses",
                        to="app.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["-calculated_at"],
                "indexes": [
                    models.Index(
                        fields=["trip", "itinerary_element", "-calculated_at"],
                        name="nodestatus_trip_elem_calc_idx",
                    )
                ],
            },
        ),
    ]
